### ISSUE TITLE
Two Suggestion:  _ set 'custom list' for SDXL specific prompting defaults & read the lora param

### ISSUE THREAD

**Issue by stephantual** [florestefano1975/comfyui-prompt-composer#1]
Hello! 
First, thank you for those nodes, I can't live without them 💯 

Second I have two suggestions: 

a) preset SDXL-specific prompting. . The #1 mistake newbies make when they use SDXL, is trying to prompt it using SD1.5 keywords. The most well known example is "(bad hands, 1.5)" - SDXL has no idea what 'bad hands' are , so the correct negative prompt is "(hands)". (source: my memory from reading an arvix  paper on the topic).
If Prompt Composer was preset with the 'official' (i realize there's not really any such list, but there are approximations), we would see people use better prompts, rather than the usual nonsensical stuff like 8K MASTERPIECE EPIC stuff that's floating around.

b) I'm reaching here, but I know there's a way to feed the loras (and sometimes embedding) dynamically from loading those that support meta data. In an ideal world, I'd drop a lora node, drag it to a custom prompt encoder node and be presented with switches for the items i want on or off. 

I realize this is probabably a ton of work, but I love those nodes and thought these would be nice additions :) 

Thank you again! 👍

**Comment by florestefano1975** [comment]
Users have full freedom to use Custom Lists to insert portions of prompts or complete prompts suited to SDXL templates. It would be too complicated to look for a standard, and it would not be right to impose it.
As for LoRA, a suitable workflow must be studied to incorporate them.
Thank you for your observations!
