### ISSUE TITLE
Custom Lists Request

### ISSUE THREAD

**Issue by Latentnaut** [florestefano1975/comfyui-prompt-composer#2]
Hi there!

I am really enjoying Portrait Master and now giving a chance to Prompt Composer.

I have some suggestion for the Custom Lists node:

- Be able to create different custom lists "groups", depending on the folders you create inside custom-lists folders.
For example, I could have 3 folders in custom-lists: Face, Camera, Background.

- Second, be able to same the folder in another route, so that it's not dangerous to overwrite your lists with any update.

- Third, change the weight bar for the "narrow version", because it saves space and it more visually pleasant.

- And lastly, be able to config in config file the max and min values of the weights, as sometimes -2 o 2 is not enough for some prompts.

They are just suggestions, I would like to know if you are willing to develope more this pack.

Thank you!

**Comment by tiosolid** [comment]
> Be able to create different custom lists "groups", depending on the folders you create inside custom-lists folders.
For example, I could have 3 folders in custom-lists: Face, Camera, Background.

> Third, change the weight bar for the "narrow version", because it saves space and it more visually pleasant.


I will try to send a PR with these soon!

EDIT: Done, hope it gets approved! https://github.com/florestefano1975/comfyui-prompt-composer/pull/6
